name: engranatge

services:
  db:
    container_name: engranatge-db
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: engranatge
      POSTGRES_USER: engranatge
      POSTGRES_PASSWORD: engranatge
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: engranatge-pgdata
