// Generated by scripts/derive-letter-equivalences.ts — do not edit by hand.
// Re-run `pnpm derive-letter-equivalences` to refresh it.
//
// Which plain letters a letter outside a–z stands for, so a company whose name
// is spelled with one is still found at the web address it registered: a firm
// called Straßenbau lives at strassenbau.de, and Nørgaard at norgaard.dk.
//
// Every row was read out of the Unicode data Node ships rather than typed here.
//
// 50 letters in the same range are left out, because no language in that
// data places them against plain letters at all:
//   ĸ ŋ ŧ ƀ ƃ ƅ ƈ ƌ ƒ ƕ ƙ ƚ ƛ ƞ ƣ ƥ ƨ ƪ ƫ ƭ ƴ ƶ ƹ ƺ ƻ ƽ
//   ƿ ǀ ǁ ǂ ǃ ǝ ǥ ȝ ȡ ȣ ȥ ȴ ȵ ȶ ȷ ȼ ȿ ɀ ɂ ɇ ɉ ɋ ɍ ɏ
// They keep their own spelling and so still find nothing. They are letters of
// languages this product has never been asked about; placing them would need a
// fold that knows those languages, not a spelling of them in a–z.
export const EQUIVALENT_LETTERS: ReadonlyMap<string, string> = new Map([
	['ß', 'ss'],
	['æ', 'ae'],
	['ð', 'd'],
	['ø', 'o'],
	['þ', 'th'],
	['đ', 'd'],
	['ħ', 'h'],
	['ı', 'i'],
	['ł', 'l'],
	['œ', 'oe'],
	['ƍ', 'zw'],
	['ƾ', 'ts'],
	['ȸ', 'db'],
	['ȹ', 'qp'],
])
