/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as EmailsIndexRouteImport } from './routes/emails/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as PagesIdRouteImport } from './routes/pages/$id'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/pages/$id': typeof PagesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/pages/$id': typeof PagesIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/emails': typeof EmailsIndexRoute
  '/pages': typeof PagesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/pages/$id': typeof PagesIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies/$slug'
    | '/pages/$id'
    | '/companies/'
    | '/emails/'
    | '/pages/'
    | '/profile/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/companies/$slug'
    | '/pages/$id'
    | '/companies'
    | '/emails'
    | '/pages'
    | '/profile'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/companies/$slug'
    | '/pages/$id'
    | '/companies/'
    | '/emails/'
    | '/pages/'
    | '/profile/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  PagesIdRoute: typeof PagesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/': {
      id: '/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  PagesIdRoute: PagesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  EmailsIndexRoute: EmailsIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
