/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedResearchIndexRouteImport } from './routes/_authed/research/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedPagesIndexRouteImport } from './routes/_authed/pages/index'
import { Route as AuthedEmailsIndexRouteImport } from './routes/_authed/emails/index'
import { Route as AuthedDocumentsIndexRouteImport } from './routes/_authed/documents/index'
import { Route as AuthedCompaniesIndexRouteImport } from './routes/_authed/companies/index'
import { Route as AuthedCalendarIndexRouteImport } from './routes/_authed/calendar/index'
import { Route as AuthedResearchRunsRouteImport } from './routes/_authed/research/runs'
import { Route as AuthedResearchIdRouteImport } from './routes/_authed/research/$id'
import { Route as AuthedPagesIdRouteImport } from './routes/_authed/pages/$id'
import { Route as AuthedEmailsInboxesRouteImport } from './routes/_authed/emails/inboxes'
import { Route as AuthedEmailsThreadIdRouteImport } from './routes/_authed/emails/$threadId'
import { Route as AuthedDocumentsIdRouteImport } from './routes/_authed/documents/$id'
import { Route as AuthedCompaniesBoardRouteImport } from './routes/_authed/companies/board'
import { Route as AuthedCompaniesSlugRouteImport } from './routes/_authed/companies/$slug'
import { Route as AuthedSettingsProfileIndexRouteImport } from './routes/_authed/settings/profile/index'
import { Route as AuthedSettingsOrganizationIndexRouteImport } from './routes/_authed/settings/organization/index'
import { Route as AuthedSettingsMcpIndexRouteImport } from './routes/_authed/settings/mcp/index'
import { Route as AuthedSettingsApiKeysIndexRouteImport } from './routes/_authed/settings/api-keys/index'
import { Route as AuthedSettingsProfileTemplatesRouteImport } from './routes/_authed/settings/profile/templates'
import { Route as AuthedSettingsOrganizationTemplatesRouteImport } from './routes/_authed/settings/organization/templates'
import { Route as AuthedSettingsOrganizationSpendRouteImport } from './routes/_authed/settings/organization/spend'
import { Route as AuthedSettingsOrganizationPolicyRouteImport } from './routes/_authed/settings/organization/policy'
import { Route as AuthedSettingsOrganizationMembersRouteImport } from './routes/_authed/settings/organization/members'
import { Route as AuthedSettingsOrganizationIndustriesRouteImport } from './routes/_authed/settings/organization/industries'
import { Route as AuthedSettingsMcpConnectionsRouteImport } from './routes/_authed/settings/mcp/connections'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedResearchIndexRoute = AuthedResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPagesIndexRoute = AuthedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmailsIndexRoute = AuthedEmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDocumentsIndexRoute = AuthedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCompaniesIndexRoute = AuthedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCalendarIndexRoute = AuthedCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedResearchRunsRoute = AuthedResearchRunsRouteImport.update({
  id: '/research/runs',
  path: '/research/runs',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedResearchIdRoute = AuthedResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPagesIdRoute = AuthedPagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmailsInboxesRoute = AuthedEmailsInboxesRouteImport.update({
  id: '/emails/inboxes',
  path: '/emails/inboxes',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEmailsThreadIdRoute = AuthedEmailsThreadIdRouteImport.update({
  id: '/emails/$threadId',
  path: '/emails/$threadId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDocumentsIdRoute = AuthedDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCompaniesBoardRoute = AuthedCompaniesBoardRouteImport.update({
  id: '/companies/board',
  path: '/companies/board',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCompaniesSlugRoute = AuthedCompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsProfileIndexRoute =
  AuthedSettingsProfileIndexRouteImport.update({
    id: '/settings/profile/',
    path: '/settings/profile/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationIndexRoute =
  AuthedSettingsOrganizationIndexRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsMcpIndexRoute = AuthedSettingsMcpIndexRouteImport.update({
  id: '/settings/mcp/',
  path: '/settings/mcp/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsApiKeysIndexRoute =
  AuthedSettingsApiKeysIndexRouteImport.update({
    id: '/settings/api-keys/',
    path: '/settings/api-keys/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsProfileTemplatesRoute =
  AuthedSettingsProfileTemplatesRouteImport.update({
    id: '/settings/profile/templates',
    path: '/settings/profile/templates',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationTemplatesRoute =
  AuthedSettingsOrganizationTemplatesRouteImport.update({
    id: '/settings/organization/templates',
    path: '/settings/organization/templates',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationSpendRoute =
  AuthedSettingsOrganizationSpendRouteImport.update({
    id: '/settings/organization/spend',
    path: '/settings/organization/spend',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationPolicyRoute =
  AuthedSettingsOrganizationPolicyRouteImport.update({
    id: '/settings/organization/policy',
    path: '/settings/organization/policy',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationMembersRoute =
  AuthedSettingsOrganizationMembersRouteImport.update({
    id: '/settings/organization/members',
    path: '/settings/organization/members',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsOrganizationIndustriesRoute =
  AuthedSettingsOrganizationIndustriesRouteImport.update({
    id: '/settings/organization/industries',
    path: '/settings/organization/industries',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsMcpConnectionsRoute =
  AuthedSettingsMcpConnectionsRouteImport.update({
    id: '/settings/mcp/connections',
    path: '/settings/mcp/connections',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/companies/$slug': typeof AuthedCompaniesSlugRoute
  '/companies/board': typeof AuthedCompaniesBoardRoute
  '/documents/$id': typeof AuthedDocumentsIdRoute
  '/emails/$threadId': typeof AuthedEmailsThreadIdRoute
  '/emails/inboxes': typeof AuthedEmailsInboxesRoute
  '/pages/$id': typeof AuthedPagesIdRoute
  '/research/$id': typeof AuthedResearchIdRoute
  '/research/runs': typeof AuthedResearchRunsRoute
  '/calendar/': typeof AuthedCalendarIndexRoute
  '/companies/': typeof AuthedCompaniesIndexRoute
  '/documents/': typeof AuthedDocumentsIndexRoute
  '/emails/': typeof AuthedEmailsIndexRoute
  '/pages/': typeof AuthedPagesIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/research/': typeof AuthedResearchIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/settings/mcp/connections': typeof AuthedSettingsMcpConnectionsRoute
  '/settings/organization/industries': typeof AuthedSettingsOrganizationIndustriesRoute
  '/settings/organization/members': typeof AuthedSettingsOrganizationMembersRoute
  '/settings/organization/policy': typeof AuthedSettingsOrganizationPolicyRoute
  '/settings/organization/spend': typeof AuthedSettingsOrganizationSpendRoute
  '/settings/organization/templates': typeof AuthedSettingsOrganizationTemplatesRoute
  '/settings/profile/templates': typeof AuthedSettingsProfileTemplatesRoute
  '/settings/api-keys/': typeof AuthedSettingsApiKeysIndexRoute
  '/settings/mcp/': typeof AuthedSettingsMcpIndexRoute
  '/settings/organization/': typeof AuthedSettingsOrganizationIndexRoute
  '/settings/profile/': typeof AuthedSettingsProfileIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof AuthedIndexRoute
  '/companies/$slug': typeof AuthedCompaniesSlugRoute
  '/companies/board': typeof AuthedCompaniesBoardRoute
  '/documents/$id': typeof AuthedDocumentsIdRoute
  '/emails/$threadId': typeof AuthedEmailsThreadIdRoute
  '/emails/inboxes': typeof AuthedEmailsInboxesRoute
  '/pages/$id': typeof AuthedPagesIdRoute
  '/research/$id': typeof AuthedResearchIdRoute
  '/research/runs': typeof AuthedResearchRunsRoute
  '/calendar': typeof AuthedCalendarIndexRoute
  '/companies': typeof AuthedCompaniesIndexRoute
  '/documents': typeof AuthedDocumentsIndexRoute
  '/emails': typeof AuthedEmailsIndexRoute
  '/pages': typeof AuthedPagesIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/research': typeof AuthedResearchIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/settings/mcp/connections': typeof AuthedSettingsMcpConnectionsRoute
  '/settings/organization/industries': typeof AuthedSettingsOrganizationIndustriesRoute
  '/settings/organization/members': typeof AuthedSettingsOrganizationMembersRoute
  '/settings/organization/policy': typeof AuthedSettingsOrganizationPolicyRoute
  '/settings/organization/spend': typeof AuthedSettingsOrganizationSpendRoute
  '/settings/organization/templates': typeof AuthedSettingsOrganizationTemplatesRoute
  '/settings/profile/templates': typeof AuthedSettingsProfileTemplatesRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysIndexRoute
  '/settings/mcp': typeof AuthedSettingsMcpIndexRoute
  '/settings/organization': typeof AuthedSettingsOrganizationIndexRoute
  '/settings/profile': typeof AuthedSettingsProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/$': typeof AuthedSplatRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/companies/$slug': typeof AuthedCompaniesSlugRoute
  '/_authed/companies/board': typeof AuthedCompaniesBoardRoute
  '/_authed/documents/$id': typeof AuthedDocumentsIdRoute
  '/_authed/emails/$threadId': typeof AuthedEmailsThreadIdRoute
  '/_authed/emails/inboxes': typeof AuthedEmailsInboxesRoute
  '/_authed/pages/$id': typeof AuthedPagesIdRoute
  '/_authed/research/$id': typeof AuthedResearchIdRoute
  '/_authed/research/runs': typeof AuthedResearchRunsRoute
  '/_authed/calendar/': typeof AuthedCalendarIndexRoute
  '/_authed/companies/': typeof AuthedCompaniesIndexRoute
  '/_authed/documents/': typeof AuthedDocumentsIndexRoute
  '/_authed/emails/': typeof AuthedEmailsIndexRoute
  '/_authed/pages/': typeof AuthedPagesIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/research/': typeof AuthedResearchIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/settings/mcp/connections': typeof AuthedSettingsMcpConnectionsRoute
  '/_authed/settings/organization/industries': typeof AuthedSettingsOrganizationIndustriesRoute
  '/_authed/settings/organization/members': typeof AuthedSettingsOrganizationMembersRoute
  '/_authed/settings/organization/policy': typeof AuthedSettingsOrganizationPolicyRoute
  '/_authed/settings/organization/spend': typeof AuthedSettingsOrganizationSpendRoute
  '/_authed/settings/organization/templates': typeof AuthedSettingsOrganizationTemplatesRoute
  '/_authed/settings/profile/templates': typeof AuthedSettingsProfileTemplatesRoute
  '/_authed/settings/api-keys/': typeof AuthedSettingsApiKeysIndexRoute
  '/_authed/settings/mcp/': typeof AuthedSettingsMcpIndexRoute
  '/_authed/settings/organization/': typeof AuthedSettingsOrganizationIndexRoute
  '/_authed/settings/profile/': typeof AuthedSettingsProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/oauth/consent'
    | '/companies/$slug'
    | '/companies/board'
    | '/documents/$id'
    | '/emails/$threadId'
    | '/emails/inboxes'
    | '/pages/$id'
    | '/research/$id'
    | '/research/runs'
    | '/calendar/'
    | '/companies/'
    | '/documents/'
    | '/emails/'
    | '/pages/'
    | '/profile/'
    | '/research/'
    | '/settings/'
    | '/tasks/'
    | '/settings/mcp/connections'
    | '/settings/organization/industries'
    | '/settings/organization/members'
    | '/settings/organization/policy'
    | '/settings/organization/spend'
    | '/settings/organization/templates'
    | '/settings/profile/templates'
    | '/settings/api-keys/'
    | '/settings/mcp/'
    | '/settings/organization/'
    | '/settings/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/oauth/consent'
    | '/'
    | '/companies/$slug'
    | '/companies/board'
    | '/documents/$id'
    | '/emails/$threadId'
    | '/emails/inboxes'
    | '/pages/$id'
    | '/research/$id'
    | '/research/runs'
    | '/calendar'
    | '/companies'
    | '/documents'
    | '/emails'
    | '/pages'
    | '/profile'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/settings/mcp/connections'
    | '/settings/organization/industries'
    | '/settings/organization/members'
    | '/settings/organization/policy'
    | '/settings/organization/spend'
    | '/settings/organization/templates'
    | '/settings/profile/templates'
    | '/settings/api-keys'
    | '/settings/mcp'
    | '/settings/organization'
    | '/settings/profile'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/$'
    | '/oauth/consent'
    | '/_authed/'
    | '/_authed/companies/$slug'
    | '/_authed/companies/board'
    | '/_authed/documents/$id'
    | '/_authed/emails/$threadId'
    | '/_authed/emails/inboxes'
    | '/_authed/pages/$id'
    | '/_authed/research/$id'
    | '/_authed/research/runs'
    | '/_authed/calendar/'
    | '/_authed/companies/'
    | '/_authed/documents/'
    | '/_authed/emails/'
    | '/_authed/pages/'
    | '/_authed/profile/'
    | '/_authed/research/'
    | '/_authed/settings/'
    | '/_authed/tasks/'
    | '/_authed/settings/mcp/connections'
    | '/_authed/settings/organization/industries'
    | '/_authed/settings/organization/members'
    | '/_authed/settings/organization/policy'
    | '/_authed/settings/organization/spend'
    | '/_authed/settings/organization/templates'
    | '/_authed/settings/profile/templates'
    | '/_authed/settings/api-keys/'
    | '/_authed/settings/mcp/'
    | '/_authed/settings/organization/'
    | '/_authed/settings/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/research/': {
      id: '/_authed/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthedResearchIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/pages/': {
      id: '/_authed/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthedPagesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/emails/': {
      id: '/_authed/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof AuthedEmailsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/documents/': {
      id: '/_authed/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthedDocumentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/companies/': {
      id: '/_authed/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthedCompaniesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/calendar/': {
      id: '/_authed/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthedCalendarIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/research/runs': {
      id: '/_authed/research/runs'
      path: '/research/runs'
      fullPath: '/research/runs'
      preLoaderRoute: typeof AuthedResearchRunsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/research/$id': {
      id: '/_authed/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof AuthedResearchIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/pages/$id': {
      id: '/_authed/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof AuthedPagesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/emails/inboxes': {
      id: '/_authed/emails/inboxes'
      path: '/emails/inboxes'
      fullPath: '/emails/inboxes'
      preLoaderRoute: typeof AuthedEmailsInboxesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/emails/$threadId': {
      id: '/_authed/emails/$threadId'
      path: '/emails/$threadId'
      fullPath: '/emails/$threadId'
      preLoaderRoute: typeof AuthedEmailsThreadIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/documents/$id': {
      id: '/_authed/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthedDocumentsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/companies/board': {
      id: '/_authed/companies/board'
      path: '/companies/board'
      fullPath: '/companies/board'
      preLoaderRoute: typeof AuthedCompaniesBoardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/companies/$slug': {
      id: '/_authed/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof AuthedCompaniesSlugRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/profile/': {
      id: '/_authed/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AuthedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/': {
      id: '/_authed/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof AuthedSettingsOrganizationIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/mcp/': {
      id: '/_authed/settings/mcp/'
      path: '/settings/mcp'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof AuthedSettingsMcpIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/api-keys/': {
      id: '/_authed/settings/api-keys/'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys/'
      preLoaderRoute: typeof AuthedSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/profile/templates': {
      id: '/_authed/settings/profile/templates'
      path: '/settings/profile/templates'
      fullPath: '/settings/profile/templates'
      preLoaderRoute: typeof AuthedSettingsProfileTemplatesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/templates': {
      id: '/_authed/settings/organization/templates'
      path: '/settings/organization/templates'
      fullPath: '/settings/organization/templates'
      preLoaderRoute: typeof AuthedSettingsOrganizationTemplatesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/spend': {
      id: '/_authed/settings/organization/spend'
      path: '/settings/organization/spend'
      fullPath: '/settings/organization/spend'
      preLoaderRoute: typeof AuthedSettingsOrganizationSpendRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/policy': {
      id: '/_authed/settings/organization/policy'
      path: '/settings/organization/policy'
      fullPath: '/settings/organization/policy'
      preLoaderRoute: typeof AuthedSettingsOrganizationPolicyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/members': {
      id: '/_authed/settings/organization/members'
      path: '/settings/organization/members'
      fullPath: '/settings/organization/members'
      preLoaderRoute: typeof AuthedSettingsOrganizationMembersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/organization/industries': {
      id: '/_authed/settings/organization/industries'
      path: '/settings/organization/industries'
      fullPath: '/settings/organization/industries'
      preLoaderRoute: typeof AuthedSettingsOrganizationIndustriesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/mcp/connections': {
      id: '/_authed/settings/mcp/connections'
      path: '/settings/mcp/connections'
      fullPath: '/settings/mcp/connections'
      preLoaderRoute: typeof AuthedSettingsMcpConnectionsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCompaniesSlugRoute: typeof AuthedCompaniesSlugRoute
  AuthedCompaniesBoardRoute: typeof AuthedCompaniesBoardRoute
  AuthedDocumentsIdRoute: typeof AuthedDocumentsIdRoute
  AuthedEmailsThreadIdRoute: typeof AuthedEmailsThreadIdRoute
  AuthedEmailsInboxesRoute: typeof AuthedEmailsInboxesRoute
  AuthedPagesIdRoute: typeof AuthedPagesIdRoute
  AuthedResearchIdRoute: typeof AuthedResearchIdRoute
  AuthedResearchRunsRoute: typeof AuthedResearchRunsRoute
  AuthedCalendarIndexRoute: typeof AuthedCalendarIndexRoute
  AuthedCompaniesIndexRoute: typeof AuthedCompaniesIndexRoute
  AuthedDocumentsIndexRoute: typeof AuthedDocumentsIndexRoute
  AuthedEmailsIndexRoute: typeof AuthedEmailsIndexRoute
  AuthedPagesIndexRoute: typeof AuthedPagesIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedResearchIndexRoute: typeof AuthedResearchIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedSettingsMcpConnectionsRoute: typeof AuthedSettingsMcpConnectionsRoute
  AuthedSettingsOrganizationIndustriesRoute: typeof AuthedSettingsOrganizationIndustriesRoute
  AuthedSettingsOrganizationMembersRoute: typeof AuthedSettingsOrganizationMembersRoute
  AuthedSettingsOrganizationPolicyRoute: typeof AuthedSettingsOrganizationPolicyRoute
  AuthedSettingsOrganizationSpendRoute: typeof AuthedSettingsOrganizationSpendRoute
  AuthedSettingsOrganizationTemplatesRoute: typeof AuthedSettingsOrganizationTemplatesRoute
  AuthedSettingsProfileTemplatesRoute: typeof AuthedSettingsProfileTemplatesRoute
  AuthedSettingsApiKeysIndexRoute: typeof AuthedSettingsApiKeysIndexRoute
  AuthedSettingsMcpIndexRoute: typeof AuthedSettingsMcpIndexRoute
  AuthedSettingsOrganizationIndexRoute: typeof AuthedSettingsOrganizationIndexRoute
  AuthedSettingsProfileIndexRoute: typeof AuthedSettingsProfileIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCompaniesSlugRoute: AuthedCompaniesSlugRoute,
  AuthedCompaniesBoardRoute: AuthedCompaniesBoardRoute,
  AuthedDocumentsIdRoute: AuthedDocumentsIdRoute,
  AuthedEmailsThreadIdRoute: AuthedEmailsThreadIdRoute,
  AuthedEmailsInboxesRoute: AuthedEmailsInboxesRoute,
  AuthedPagesIdRoute: AuthedPagesIdRoute,
  AuthedResearchIdRoute: AuthedResearchIdRoute,
  AuthedResearchRunsRoute: AuthedResearchRunsRoute,
  AuthedCalendarIndexRoute: AuthedCalendarIndexRoute,
  AuthedCompaniesIndexRoute: AuthedCompaniesIndexRoute,
  AuthedDocumentsIndexRoute: AuthedDocumentsIndexRoute,
  AuthedEmailsIndexRoute: AuthedEmailsIndexRoute,
  AuthedPagesIndexRoute: AuthedPagesIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedResearchIndexRoute: AuthedResearchIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedSettingsMcpConnectionsRoute: AuthedSettingsMcpConnectionsRoute,
  AuthedSettingsOrganizationIndustriesRoute:
    AuthedSettingsOrganizationIndustriesRoute,
  AuthedSettingsOrganizationMembersRoute:
    AuthedSettingsOrganizationMembersRoute,
  AuthedSettingsOrganizationPolicyRoute: AuthedSettingsOrganizationPolicyRoute,
  AuthedSettingsOrganizationSpendRoute: AuthedSettingsOrganizationSpendRoute,
  AuthedSettingsOrganizationTemplatesRoute:
    AuthedSettingsOrganizationTemplatesRoute,
  AuthedSettingsProfileTemplatesRoute: AuthedSettingsProfileTemplatesRoute,
  AuthedSettingsApiKeysIndexRoute: AuthedSettingsApiKeysIndexRoute,
  AuthedSettingsMcpIndexRoute: AuthedSettingsMcpIndexRoute,
  AuthedSettingsOrganizationIndexRoute: AuthedSettingsOrganizationIndexRoute,
  AuthedSettingsProfileIndexRoute: AuthedSettingsProfileIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
