/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as EmailsIndexRouteImport } from './routes/emails/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as PagesIdRouteImport } from './routes/pages/$id'
import { Route as EmailsInboxesRouteImport } from './routes/emails/inboxes'
import { Route as EmailsThreadIdRouteImport } from './routes/emails/$threadId'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as SettingsOrganizationIndexRouteImport } from './routes/settings/organization/index'
import { Route as SettingsOrganizationSpendRouteImport } from './routes/settings/organization/spend'
import { Route as SettingsOrganizationMembersRouteImport } from './routes/settings/organization/members'
import { Route as SettingsOrganizationInviteRouteImport } from './routes/settings/organization/invite'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/pages/$id',
  path: '/pages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsInboxesRoute = EmailsInboxesRouteImport.update({
  id: '/emails/inboxes',
  path: '/emails/inboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsThreadIdRoute = EmailsThreadIdRouteImport.update({
  id: '/emails/$threadId',
  path: '/emails/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationIndexRoute =
  SettingsOrganizationIndexRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsOrganizationSpendRoute =
  SettingsOrganizationSpendRouteImport.update({
    id: '/settings/organization/spend',
    path: '/settings/organization/spend',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsOrganizationMembersRoute =
  SettingsOrganizationMembersRouteImport.update({
    id: '/settings/organization/members',
    path: '/settings/organization/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsOrganizationInviteRoute =
  SettingsOrganizationInviteRouteImport.update({
    id: '/settings/organization/invite',
    path: '/settings/organization/invite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/emails/$threadId': typeof EmailsThreadIdRoute
  '/emails/inboxes': typeof EmailsInboxesRoute
  '/pages/$id': typeof PagesIdRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/settings/organization/invite': typeof SettingsOrganizationInviteRoute
  '/settings/organization/members': typeof SettingsOrganizationMembersRoute
  '/settings/organization/spend': typeof SettingsOrganizationSpendRoute
  '/settings/organization/': typeof SettingsOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/emails/$threadId': typeof EmailsThreadIdRoute
  '/emails/inboxes': typeof EmailsInboxesRoute
  '/pages/$id': typeof PagesIdRoute
  '/calendar': typeof CalendarIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/emails': typeof EmailsIndexRoute
  '/pages': typeof PagesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/settings/organization/invite': typeof SettingsOrganizationInviteRoute
  '/settings/organization/members': typeof SettingsOrganizationMembersRoute
  '/settings/organization/spend': typeof SettingsOrganizationSpendRoute
  '/settings/organization': typeof SettingsOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/emails/$threadId': typeof EmailsThreadIdRoute
  '/emails/inboxes': typeof EmailsInboxesRoute
  '/pages/$id': typeof PagesIdRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/settings/organization/invite': typeof SettingsOrganizationInviteRoute
  '/settings/organization/members': typeof SettingsOrganizationMembersRoute
  '/settings/organization/spend': typeof SettingsOrganizationSpendRoute
  '/settings/organization/': typeof SettingsOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accept-invitation/$id'
    | '/companies/$slug'
    | '/emails/$threadId'
    | '/emails/inboxes'
    | '/pages/$id'
    | '/calendar/'
    | '/companies/'
    | '/emails/'
    | '/pages/'
    | '/profile/'
    | '/tasks/'
    | '/settings/organization/invite'
    | '/settings/organization/members'
    | '/settings/organization/spend'
    | '/settings/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accept-invitation/$id'
    | '/companies/$slug'
    | '/emails/$threadId'
    | '/emails/inboxes'
    | '/pages/$id'
    | '/calendar'
    | '/companies'
    | '/emails'
    | '/pages'
    | '/profile'
    | '/tasks'
    | '/settings/organization/invite'
    | '/settings/organization/members'
    | '/settings/organization/spend'
    | '/settings/organization'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/accept-invitation/$id'
    | '/companies/$slug'
    | '/emails/$threadId'
    | '/emails/inboxes'
    | '/pages/$id'
    | '/calendar/'
    | '/companies/'
    | '/emails/'
    | '/pages/'
    | '/profile/'
    | '/tasks/'
    | '/settings/organization/invite'
    | '/settings/organization/members'
    | '/settings/organization/spend'
    | '/settings/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  EmailsThreadIdRoute: typeof EmailsThreadIdRoute
  EmailsInboxesRoute: typeof EmailsInboxesRoute
  PagesIdRoute: typeof PagesIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  SettingsOrganizationInviteRoute: typeof SettingsOrganizationInviteRoute
  SettingsOrganizationMembersRoute: typeof SettingsOrganizationMembersRoute
  SettingsOrganizationSpendRoute: typeof SettingsOrganizationSpendRoute
  SettingsOrganizationIndexRoute: typeof SettingsOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/': {
      id: '/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/pages/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/inboxes': {
      id: '/emails/inboxes'
      path: '/emails/inboxes'
      fullPath: '/emails/inboxes'
      preLoaderRoute: typeof EmailsInboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$threadId': {
      id: '/emails/$threadId'
      path: '/emails/$threadId'
      fullPath: '/emails/$threadId'
      preLoaderRoute: typeof EmailsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization/': {
      id: '/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof SettingsOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization/spend': {
      id: '/settings/organization/spend'
      path: '/settings/organization/spend'
      fullPath: '/settings/organization/spend'
      preLoaderRoute: typeof SettingsOrganizationSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization/members': {
      id: '/settings/organization/members'
      path: '/settings/organization/members'
      fullPath: '/settings/organization/members'
      preLoaderRoute: typeof SettingsOrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization/invite': {
      id: '/settings/organization/invite'
      path: '/settings/organization/invite'
      fullPath: '/settings/organization/invite'
      preLoaderRoute: typeof SettingsOrganizationInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  EmailsThreadIdRoute: EmailsThreadIdRoute,
  EmailsInboxesRoute: EmailsInboxesRoute,
  PagesIdRoute: PagesIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  EmailsIndexRoute: EmailsIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  SettingsOrganizationInviteRoute: SettingsOrganizationInviteRoute,
  SettingsOrganizationMembersRoute: SettingsOrganizationMembersRoute,
  SettingsOrganizationSpendRoute: SettingsOrganizationSpendRoute,
  SettingsOrganizationIndexRoute: SettingsOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
